{"name": "not authenticated user -- @1.10 cases", "status": "broken", "statusDetails": {"message": "NameError: name 'requests' is not defined\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 15, in step_impl\n    session = eval(persons[person])\n  File \"<string>\", line 1, in <module>\n"}, "steps": [{"name": "Given alien makes post request: /reconciliation/reports_update/", "status": "broken", "statusDetails": {"message": "NameError: name 'requests' is not defined\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 15, in step_impl\n    session = eval(persons[person])\n  File \"<string>\", line 1, in <module>\n"}, "start": 1610701619311, "stop": 1610701619312}], "parameters": [{"name": "url", "value": "/reconciliation/reports_update/"}, {"name": "method", "value": "post"}, {"name": "bool", "value": "True"}], "start": 1610701619310, "stop": 1610701619312, "uuid": "7fc32762-f292-43f4-8a47-f6a3ee956574", "historyId": "9678365b203b9eeb5afccf65c6db932d", "fullName": "features/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}