{"name": "not authenticated user -- @1.9 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/reports_update/", "status": "passed", "start": 1610743456323, "stop": 1610743456348}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1610743456348, "stop": 1610743456348}], "parameters": [{"name": "url", "value": "/reconciliation/reports_update/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610743456322, "stop": 1610743456348, "uuid": "6788e6c8-3d5b-4c32-b58a-cd6913c1155e", "historyId": "ac58806490ce30707c69c23b6a43d454", "fullName": "features/II-Reconciliation/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}