{"name": "not authenticated user -- @1.15 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/status_accounts/", "status": "passed", "start": 1610713914069, "stop": 1610713914100}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1610713914101, "stop": 1610713914102}], "parameters": [{"name": "url", "value": "/reconciliation/status_accounts/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610713914067, "stop": 1610713914102, "uuid": "abc670a1-cfcd-4f45-8a50-9498c1779ec9", "historyId": "d0e9299b688c03ad05401c3286bf49f9", "fullName": "features/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}