{"name": "not authenticated user -- @1.9 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/reports_update/", "status": "passed", "start": 1610694105017, "stop": 1610694105047}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1610694105048, "stop": 1610694105048}], "parameters": [{"name": "url", "value": "/reconciliation/reports_update/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610694105015, "stop": 1610694105048, "uuid": "76f42fa3-f387-44ea-beac-000a1021ce70", "historyId": "ac58806490ce30707c69c23b6a43d454", "fullName": "features/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}