{"name": "not authenticated user -- @1.9 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/reports_update/", "status": "passed", "start": 1611333543468, "stop": 1611333543509}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1611333543510, "stop": 1611333543510}], "parameters": [{"name": "url", "value": "/reconciliation/reports_update/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1611333543467, "stop": 1611333543510, "uuid": "15bc8737-ed2e-4a0e-aa1b-789ae961105e", "historyId": "ac58806490ce30707c69c23b6a43d454", "fullName": "features/II-Reconciliation/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}