{"name": "not authenticated user -- @1.3 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/all_users_data/", "status": "passed", "start": 1610744395428, "stop": 1610744395456}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1610744395456, "stop": 1610744395457}], "parameters": [{"name": "url", "value": "/reconciliation/all_users_data/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610744395427, "stop": 1610744395457, "uuid": "ddf5b6e2-501a-4624-83f2-74221660c7bf", "historyId": "ea3eabf110f4edf4621eab3e43164087", "fullName": "features/II-Reconciliation/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}