{"name": "manager user -- @1.1 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given manager makes post request: /reconciliation/status/ and True", "status": "passed", "start": 1610699921761, "stop": 1610699921842}, {"name": "Then check response of request: You do not have permission to perform this action. is True", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610699921843, "stop": 1610699921844}], "parameters": [{"name": "url", "value": "/reconciliation/status/"}, {"name": "method", "value": "post"}, {"name": "bool", "value": "True"}], "start": 1610699921758, "stop": 1610699921845, "uuid": "67db2bdd-f783-4d22-86a1-b309481413fd", "historyId": "d0bb2216d6e1f1a78f8cdc17e840afea", "fullName": "features/III-reconciliation_access.feature:manager user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}