{"name": "manager user -- @1.12 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given alien makes get request: /reconciliation/services_compensations/", "status": "passed", "start": 1610694652252, "stop": 1610694652276}, {"name": "Then check response of request: You do not have permission to perform this action. is True", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610694652276, "stop": 1610694652277}], "parameters": [{"name": "url", "value": "/reconciliation/services_compensations/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610694652251, "stop": 1610694652278, "uuid": "55a69e08-9c96-4c28-913a-47d0a0b63182", "historyId": "91d7e2238c7fd9d1efda3c276c756a58", "fullName": "features/III-reconciliation_access.feature:manager user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}