{"name": "check hr import", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 175, in step_impl\n    assert len(rows) > 0\n"}, "steps": [{"name": "Given clear reconciliationuserpropaccount table", "status": "passed", "start": 1611335643279, "stop": 1611335643318}, {"name": "And activate hr_import", "status": "passed", "start": 1611335643318, "stop": 1611335643640}, {"name": "And pause - 10 sec(s)", "status": "passed", "start": 1611335643641, "stop": 1611335653645}, {"name": "Then check reconciliationuserpropaccount table after hr import", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 175, in step_impl\n    assert len(rows) > 0\n"}, "start": 1611335653646, "stop": 1611335653698}], "start": 1611335643277, "stop": 1611335653702, "uuid": "ffc216ac-46fb-4491-965b-cf2ba05d5c25", "historyId": "f0498b976f875a2b28959ccfe3337637", "fullName": "features/II-Reconciliation/I-reconciliation_risk.feature:check hr import", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "check all user_data"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}