{"name": "not authenticated user -- @1.9 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/reports_update/", "status": "passed", "start": 1610783586045, "stop": 1610783586070}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1610783586071, "stop": 1610783586071}], "parameters": [{"name": "url", "value": "/reconciliation/reports_update/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610783586044, "stop": 1610783586071, "uuid": "a11cd00e-1b78-482a-bc58-042a32b5af40", "historyId": "ac58806490ce30707c69c23b6a43d454", "fullName": "features/II-Reconciliation/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}