{"name": "manager user -- @1.11 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given manager makes post request: /reconciliation/status/", "status": "passed", "start": 1610698581183, "stop": 1610698581201}, {"name": "Then check response of post request: You do not have permission to perform this action. is True", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610698581202, "stop": 1610698581203}], "parameters": [{"name": "url", "value": "/reconciliation/status/"}, {"name": "method", "value": "post"}, {"name": "bool", "value": "True"}], "start": 1610698581182, "stop": 1610698581203, "uuid": "1fd44115-2e78-4c66-9c7b-7605ca1202a9", "historyId": "458eb0d7b8a0b20ad80d9c9bfeb1e49a", "fullName": "features/III-reconciliation_access.feature:manager user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}