{"name": "check hr import", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 231, in step_impl\n    assert False\n"}, "steps": [{"name": "Given download all_users_data.xlsx", "status": "passed", "start": 1610722750468, "stop": 1610722751180}, {"name": "When parse downloaded all_users_data.xlsx to compare with data from /reconciliation/all_users_data/", "status": "passed", "start": 1610722751181, "stop": 1610722751232}, {"name": "Then compare downloaded data with data from /reconciliation/all_users_data/", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 231, in step_impl\n    assert False\n"}, "start": 1610722751233, "stop": 1610722751502}], "start": 1610722750467, "stop": 1610722751503, "uuid": "0c859cb3-53a0-44ae-ada5-b384117dd9f4", "historyId": "f0498b976f875a2b28959ccfe3337637", "fullName": "features/II-Reconciliation/II-reconciliation_risk.feature:check hr import", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "check all user_data"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}