{"name": "check hr import", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 223, in step_impl\n    assert context.actual_result in expected_result\n"}, "steps": [{"name": "Given download all_users_data.xlsx", "status": "passed", "start": 1610713680579, "stop": 1610713681140}, {"name": "When parse downloaded all_users_data.xlsx to compare with data from /reconciliation/all_users_data/", "status": "passed", "start": 1610713681141, "stop": 1610713681188}, {"name": "Then compare downloaded data with data from /reconciliation/all_users_data/", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 223, in step_impl\n    assert context.actual_result in expected_result\n"}, "start": 1610713681189, "stop": 1610713681336}], "start": 1610713680578, "stop": 1610713681338, "uuid": "daf60c70-4e16-451b-a66b-b4d3d8d2507a", "historyId": "f0498b976f875a2b28959ccfe3337637", "fullName": "features/II-reconciliation_risk.feature:check hr import", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "check all user_data"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}