{"name": "not authenticated user -- @1.3 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/all_users_data/", "status": "passed", "start": 1610743456147, "stop": 1610743456173}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1610743456173, "stop": 1610743456174}], "parameters": [{"name": "url", "value": "/reconciliation/all_users_data/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610743456146, "stop": 1610743456174, "uuid": "5eb4c677-e873-4f92-93b4-d942bfb43999", "historyId": "ea3eabf110f4edf4621eab3e43164087", "fullName": "features/II-Reconciliation/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}